name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-artifacts
        path: |
          build/dist/js/productionExecutable/
          build/dist/wasm/productionExecutable/
        if-no-files-found: error
